language: go
go:
  - '1.10'
git:
  depth: 1

sudo: false

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - |-
    mkdir -p artifacts
    for GOOS in linux darwin
    do
      env GOOS=$GOOS GOARCH=amd64 go build -o gen3-fuse
      zip gen3fuse_$GOOS.zip gen3-fuse && mv gen3fuse_$GOOS.zip artifacts/. && rm gen3-fuse
    done

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "LgObHh04RLtzfbBDzlpxeSpHTWMzJpSbqyuVUZlJyn8SM32vU39oUSwEuF1cb1qtJwcfhF3cN19kFFmv8FqGosyDnvfrYj1hwvvnh2akMzqgy1bY9UogvrFOuAc118uaW0d7ycdiDGn3OdqoYvgKQKQhcbHrwfmHNUqueHVErXPf76lLjFsTbVVceWzdDHUSJCgjaF8BOPcHI11eV186+LmhEdlXoeMxFrLNRRGOKCCDpCxEYpscUryuKolsQ9308xS5zial+mt2eTZXVqQNVhyuR5/RGIBqGdGOH6G/aLG4CV3NWEtWd/th+JFbWXEDpRcDX+nYQZTlBJ53mryPw/MFyjhnN/rKsG5jbh5XUrIyq8Cf1D9EyyxBeUNHdEyBX5BWiGzpvG+GAnAvyGs5NcwAphCKgOXRlZP+JyFzKo1sja8TRrfhpe1ltgVszMbnt8z1cxyQ7WIEUJmBWvNN+Sbku0cfVlrksRjphFm1K4ahWFZQgQ00QtEvFumCLDmoIBzIWVxzkKdW6TlJ+yNCYDSQhs5al58I/bjdHr9bFWkIGvxcgtXXnT2uO2lWtU7PTvlc2aD/ACaNdkvaatGgyD8tno0hjpDMY/OUN06I9ggMnm+YqC/s9qIqBhDpPUNvI/3PlJejmx9H+C0aZEk3Gnnp3IvttJjSEdlzCQOwRVE="
    file:
      - artifacts/gen3fuse_darwin.zip
      - artifacts/gen3fuse_linux.zip
    on:
      branch: master
      tags: true
    # creds are in travis env var settings, there is a bug with travis that putting the key here results in generating  signature that does not match
  - provider: s3
    bucket: gen3-fuse-builds
    local-dir: artifacts
    upload-dir: "$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
