language: go
go:
  - '1.10'
git:
  depth: 1

sudo: false

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - |-
    mkdir -p artifacts
    for GOOS in linux darwin
    do
      env GOOS=$GOOS GOARCH=amd64 go build -o gen3-fuse
      zip gen3fuse_$GOOS.zip gen3-fuse && mv gen3fuse_$GOOS.zip artifacts/. && rm gen3-fuse
    done

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "JMkrio56JrAJuabS0EnOLl68qYHMaEuB6km46LCExEkPLhYvw/Iqo0QqMBMvQgfrF1CfPuLYZ5TviK9hElwbe+/aymE/B09FIA5idx+IisYYUWUZTtmU5yYGhgo1SAUOpRxO1guWBmKZ/ftuviN5gxomErX+6MN1y0MV6nC/NVXfYE5XUEN3rcSs+rIZESGfnfkEMovTCSL89YW402/kqrwNbAtat4Y4nPF5hkMqJf344WnZoPEVGd0dQANjOYNMpsoHa8n7OtBsbSp0QV0phj2DkXh+X2OHo3myVa12n2KP5v/ZLQ5stglvNLmnPy7dm5rc3WAGphBBtRa20QzGShvm7ksu6z2XhzhEJD3RbrU2X3a8HOEANmyCwhElXv0B9Z1V8QYAOP+6ILx/zIJJw4W/JBZiz38gqU9nJ0NEje6pqrRlGBseeT9BqAeK86j4PSDHZoP1de4sMRE4cmpHKkHRP4pIxlFh8Du9DkLtJhq80PMbgVLdDaDENi0jqPEyXSyTpRIiz0K/HWks0hhvC777KVEsFdTN98ayhtTz/kQ8a120FphAat3jbvI68gaovWVcziJFMrG7XEfNbf84W6XyxfnLISwr1aVoLiaCPP1zjKq3vWa20HJYKDULL7VtKTYHn8PYmTASCdEzfeTqZZud8MUARfO+jzi2Ep0cRpE="
    file:
      - artifacts/gen3fuse_darwin.zip
      - artifacts/gen3fuse_linux.zip
    on:
      branch: master
      tags: true
    # creds are in travis env var settings, there is a bug with travis that putting the key here results in generating  signature that does not match
  - provider: s3
    bucket: gen3-fuse-builds
    local-dir: artifacts
    upload-dir: "$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
