language: go
go:
  - '1.10'
git:
  depth: 1

sudo: false

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - |-
    mkdir -p artifacts
    for GOOS in linux darwin
    do
      env GOOS=$GOOS GOARCH=amd64 go build -o gen3-fuse
      zip gen3fuse_$GOOS.zip gen3-fuse && mv gen3fuse_$GOOS.zip artifacts/. && rm gen3-fuse
    done

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "Vpz/J/20OU1ZWOkY7AdtDX1Z7iE47pFbP5Bq9XgYBrWmqK3Iw/u6FtM22qOuzJtkmwG6qDuRwnNn1Ep5vphC0QxZopggpe19ngP05IpdicOPgUuS92fzqvpOGIBRD7PHqtQQLRtRSHoF8LRjmabxkjiBR6Xglgd37Qj2YXwFG+KyaJjkoG/3/w9dDdF87LrdOrWAvS0fVIZRs+Vk6VxalMJjGuzIcI27jgGAdML7dSK/UY1Fh/9EtrU7f1YNhGw4Gzx9neVCFtIfGNDeVGzgF5j4LcGzNNwOrAR7eVLso5vqmqVgWR4eXN/5GFh/UzVQ/QyUi9Ioo3AUQaJCdrKnVU1bRAuJ2Cu3jvlelmfzozTb/6ORFnR31mmxj3FKd4TJVBdHcfvG20lCyCYCy7yvQpPgcAr+nao3Mrh+omnycQ5CFUirnHv2GSvcbgjeq058AA/8qLwyuTz8S6PyIsw1RTaptdg0jirCxc6dCBOgMEpmcamQFajH/70k7wTkmPXxZ8x40qrZCJb1YlcqY2XO5evf0jOPdQt2zLKNMxeNPC5UT2EiCWz/gP0/VyqVwaQIy5lv/TCdT/8MrBWxrKx/ybxwg9Ja4xxDBJ0F8HghnYKAPd7i0mC8zkP5wcWzyqi5ET5hvZNcaMvJLGhA+ZphvR0mHh71Vp7/XoBd3P/ol+U="
    file:
      - artifacts/gen3fuse_darwin.zip
      - artifacts/gen3fuse_linux.zip
    on:
      branch: master
      tags: true
    # creds are in travis env var settings, there is a problem with travis that putting the key here results in generating  signature that does not match
  - provider: s3
    bucket: gen3-fuse-builds
    local-dir: artifacts
    upload-dir: "$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
