FencePresignedURLPath: "/user/data/download/%s"
FenceAccessTokenPath: "/user/credentials/api/access_token"

IndexdBulkFileInfoPath: "/index/bulk/documents"

WTSFenceConnectPath: "/oauth2/authorization_url"
WTSAccessTokenPath: "/token?expires=%d"

LogFilePath: "fuse_log.txt"